### ISSUE TITLE
Update the visualization to the round 19

### ISSUE THREAD

**Issue by joanhey** [ajdust/tfbvis#1]
Hi, 
really good work and it was really helpful to me.

Now it's official the round 19.
If you update the visualization, we can link to it.

Thank you

**Comment by ajdust** [comment]
Thanks @joanhey. The data for Round 19's [Citrine run](https://tfb-status.techempower.com/results/4c536195-90ff-40b8-8636-a719318a864b) is there now. Note it appears the [Round 19 Azure run](https://tfb-status.techempower.com/results/9a267248-17b0-4080-ac45-a50d25b4fc2a) did not record any Dstat data.

Cheers
