### ISSUE TITLE
The update visualization

### ISSUE THREAD

**Issue by joanhey** [ajdust/tfbvis#2]
It's showing the result for 1 query/req.
Need to show the results for 20 queries/req.

**Comment by ajdust** [comment]
@joanhey thanks for the input. I'm not sure what you mean. `query` should already be using the 20 queries/req results. Can you be more specific about the error? Thanks.

**Comment by joanhey** [comment]
The results need to show the 20 queries results.
https://www.techempower.com/benchmarks/#section=data-r19&hw=ph&test=query
![DeepinScreenshot_Seleccionar área_20200624140759](https://user-images.githubusercontent.com/249085/85553381-2e4b8300-b624-11ea-82c8-7e3dc7e7ea02.png)

**Comment by ajdust** [comment]
As I said, if you choose the test=query option in the dropdown, it is the 20 queries results. It is already taken into account. Let me know if there is a mistake I'm not seeing.

![image](https://user-images.githubusercontent.com/9620665/85605170-ccc8eb80-b606-11ea-8018-b619ba1d6b60.png)

**Comment by joanhey** [comment]
Sorry, the problem is in the Update test, not in the query test.

**Comment by ajdust** [comment]
Ah, I see what you mean now. Thanks for catching that! I overlooked that detail of the update test. I'll make that quick fix later today.
