### ISSUE TITLE
New update to Round 20

### ISSUE THREAD

**Issue by joanhey** [ajdust/tfbvis#4]
Hi, thank you for your work
New data for   Round 20

https://tfb-logs.techempower.com/Round%2020/ 
https://github.com/TechEmpower/FrameworkBenchmark/issue/#5709
https://github.com/TechEmpower/FrameworkBenchmarks/issues/5709

And Round 19 is here to compare:
https://ajdust.github.io/tfbvis/

**Comment by ajdust** [comment]
Thanks for the heads up @joanhey, I added the data for Round 20. It looks like https://tfb-status.techempower.com/ is still down but I was able to pull the data with the https://tfb-logs.techempower.com/Round%2020/ link you provided.

Once https://tfb-status.techempower.com/ is back up I will verify it has same data.

**Comment by ajdust** [comment]
[TFB status](https://tfb-status.techempower.com/) is back up and currently showing a new benchmark starting today 2021-01-18, so I assume the banner 'Official Round 20 runs are now in progress' is not current. Data for [2020-12-29 (Round 20)](https://tfb-status.techempower.com/results/f78282e3-ed37-4e7c-9862-3163de23b23b) is a match :+1:
